export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";

export const FETCH_DRONE_DATA = 'COMMAND/FETCH_DRONE_DATA';
export const FETCH_DRONE_DATA_SUCCESS = 'EVENT/FETCH_DRONE_DATA_SUCCESS';
// export const FETCH_DRONE_DATA_FAILURE = 'EVENT/FETCH_DRONE_DATA_FAILURE';
export const START_POLLING = 'COMMAND/START_POLLING';
export const STOP_POLLING = 'COMMAND/STOP_POLLING';